public class Fruits
{
    public static String[] fruitList = {"Abiu", "acai", "acerola", "ackee", "apple", "appleberry", "apricot", 
                "aprium", "araca-boi", "arrowroot", "atemoya", "avocado", "bacuri", "bael", "banana", 
                "barbadine", "barbados cherry", "barberry", "beach plum", "bearberry", "bignay", 
                "bilberry", "bilimbi", "black apple", "black cherry", "black currant", 
                "black raspberry", "black sapote", "blackberry", "blood orange", "blueberry", 
                "breadfruit", "cantaloupe", "capulin cherry", "star fruit", 
                "cashew apple", "cavendish", "ceriman", "chayote", "cherry", "cherimoya", "clementine", 
                "coconut", "cranberry", "currant", "date", "dacca", "damson", "dragon fruit", "drupe", "durian", 
                "elderberry", "feijoa", "fig", "finger lime", "gooseberry", "goldfinger", "grape", "grapefruit", 
                "guava", "hackberry", "hawthorn", "honeydew melon", "horned melon", "huckleberry", 
                "illawarra plum", "imbe", "indian fig", "indian plum", "jaboticaba", "jackfruit", "jambolan", 
                "jatoba", "jelly palm", "jostaberry", "jujube", "jungle plum", "kadota fig", "kaempferia galanga", 
                "kaki", "kakadu plum", "kalingag", "karonda", "kashmere plum", "kei apple", "key lime", "kiwi", 
                "kiwi berry", "kitembilla", "klamath plum", "kluay khai", "kokum", "kumquat", "lemon", "lime", 
                "loganberry", "longan", "loquat", "lychee", "macadamia", "mamoncillo", "mandarin", "mango", 
                "mangosteen", "mayapple", "melon", "minneola", "mulberry", "musk melon", "nance", "nectarine", 
                "olive", "orange", "pandanus", "papaya", "passion fruit", "pawpaw", "peach", "pear", "persimmon", 
                "pineapple", "pinot blanc", "plantain", "plum", "pomegranate", "prickly pear", "pomelo", "pulasan", 
                "pumpkin", "quince", "rambutan", "rambutan", "raspberry", "red dacca", "redcurrant", "rhubard", 
                "rose hip", "rowan", "salal berry", "salak", "salmonberry", "sarsaparilla", "satsuma", 
                "saskatoon berry", "sea buckthorn", "serviceberry", "shasta berry", "sharon fruit", 
                "sloe", "snake fruit", "soncoya", "sour cherry", "soursop", "spanish lime", "star apple", 
                "starfruit", "strawberry", "sugar apple", "tamarillo", "tamarind", "tangerine", "tayberry", 
                "tayberry", "ugli fruit", "umbra", "vanilla bean", "watermelon", "whortleberry", "white sapote", 
                "whitecurrant", "wolfberry", "woolly apple", "youngberry", "xigua", "yumberry", "zill", 
                "zinfandel grape", "ziziphus", "zucchini"};
}